version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "daily"
    groups:
      junit:
        patterns:
          - "org.junit*"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
