version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "daily"
    groups:
      junit:
        patterns:
          - "org.junit*"
    ignore:
      - dependency-name: "org.junit*"
        update-types:
          - "version-update:semver-major"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
